#!/bin/sh

set_gpio() {
	[ "$2" -eq 1 ] && gpio set $1 || gpio clear $1
	sleep 1
}

# Generic MT7601U
if [ "$1" = "mt7601u-generic" ]; then
	modprobe mt7601u
	exit 0
fi

# Generic RTL8188EU
if [ "$1" = "rtl8188eu-generic" ]; then
	modprobe 8188eu
	exit 0
fi

# Generic RTL8188FU
if [ "$1" = "rtl8188fu-generic" ]; then
	modprobe 8188fu
	exit 0
fi


# T40n
if [ "$1" = "ssv6155-t40n" ]; then
	modprobe ssv6155
	exit 0
fi

exit 1
